export const DROP_PREVIEW_TYPES = {
    QUICK_LIST: 'DROP_PREVIEW_QUICK_LIST',
    QUICK_GRID: 'DROP_PREVIEW_QUICK_GRID',
    FULL_PAGE: 'DROP_PREVIEW_FULL_PAGE',
}

export const POD_VIEW_TYPES = {
    LIST_VIEW: 'POD_VIEW_LIST',
    GRID_VIEW: 'POD_VIEW_GRID',
    GENERIC_POD_VIEW: 'POD_VIEW_GENERIC',
}

export const DROP_REVIEW_TYPES = {
    GENERIC_DROP_REVIEW: 'DROP_REVIEW_GENERIC',
}

export const GOOGLE_ANALYTICS_ITEM_CATEGORIES = {
    PREVIEW_DROP: 'PREVIEW_DROP',
    VIEW_POD: 'VIEW_POD',
    REVIEW_DROP: 'REVIEW_DROP',
}

export const GOOGLE_ANALYTICS_LOG_SHARE_TYPES = {
    POD_SHARE: 'POD_SHARE',
}
