export const TOGGLE_BOTTOM_BAR_VISIBLE = 'TOGGLE_BOTTOM_BAR_VISIBLE'
export const TOGGLE_FORCE_ONBOARDING = 'TOGGLE_FORCE_ONBOARDING'

export const CHOOSE_POD = 'CHOOSE_POD'
export const CHOOSE_DROP = 'CHOOSE_DROP'
export const SET_USER_PARAMS = 'SET_USER_PARAMS'
export const SET_INVITATION_PARAMS = 'SET_INVITATION_PARAMS'

export const SET_CONFIRMATION_RESULTS = 'SET_CONFIRMATION_RESULTS'
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE'

export const SET_NOTIFICATION_BAR_MESSAGE = 'SET_NOTIFICATION_BAR_MESSAGE'

export const TOGGLE_UPLOADING_DROP = 'TOGGLE_UPLOADING_DROP'
export const ADD_LOADING_ENGAGEMENT_DROP = 'ADD_LOADING_ENGAGEMENT_DROP'
export const REMOVE_LOADING_ENGAGEMENT_DROP = 'REMOVE_LOADING_ENGAGEMENT_DROP'

export const SET_DROP_STORAGE_ARRAY = 'SET_DROP_STORAGE_ARRAY'
export const SET_UPLOADING_DROP_POD_IDS = 'SET_UPLOADING_DROP_POD_IDS'
export const SET_DROP_FUNCTIONALITY = 'SET_DROP_FUNCTIONALITY'
export const TOGGLE_REFETCH_ON_NOTIFICATION = 'TOGGLE_REFETCH_ON_NOTIFICATION'
